### ISSUE TITLE
PAUL-JULIUS-IKON

### ISSUE THREAD

**Issue by canon20paul** [Irirwanirira/My-portofolio#6]
- I suggest using rem and em as units in addition to applying this on you root selector as this is a more effective way and units for responsiveness.
- Having initiated a Font family in you Parent files like the Body its unnecessary to have repetitions else where

**Comment by Irirwanirira** [comment]
@canon20paul,
Thank you for your contribution.

**Comment by Irirwanirira** [comment]
@canon20paul Thank you for your time.
